### PR TITLE
Minimal conversion to pytest+hypothesis

### PR DESCRIPTION
**Pull request by mgorny**
The purpose of this PR is to get the test suite working on pytest, without depending on nose in any way and while making minimal changes to the existing code.

What I had to do is:
- move tests from `__init__.py` to `test_*.py`
- replace `nose_random` with `hypothesis`

…and that's pretty much it. It's fine to use unittest-style classes with pytest. Hypothesis seems to integrate neatly in place of `nose_random`.

### CODE REVIEW

**Comment by fzumstein** [comment]
have you seen https://github.com/xlwings/jsondiff/pull/51 ? How does it compare?

**Comment by mgorny** [comment]
Fixes #44.

**Comment by mgorny** [comment]
> have you seen #51 ? How does it compare?

It roughly tries to minimize the amount of changes and make the code look as close to the original as possible. Also hypothesis is pretty neat when things start failing.

**Comment by fzumstein** [comment]
thanks!

**Comment by mgorny** [comment]
Thanks a lot!

**Pull request merged**
