### PR TITLE
Introduce YAML support

### LINKED ISSUE #66: Introduce YAML support for cli
It would be cool to have built-in support for YAML on the CLI. Most of my data is YAML and I end
up having to pipe it through yq so native would be nice.

Since this only affects the cli, I propose leaving all of the current structure alone. We would need a new loader/dumper pair and a `--format` parameter so the user can hint their file type. We could get
fancy and auto-detect the type but I'm not keen on that yet.

There should also be explicit tests for all of the loader/dumper variants.

### PR DESCRIPTION
**Pull request by corytodd**
This introduces YAML support to the CLI. No changes to the library are intended. There are some minor changes to the CLI help menu but otherwise this is only a feature add.

- CLI help now includes the default parameters when --help is specified
- CLI --syntax is now limited to the list of built-in syntaxes (I always forget how to spell symmetric :) )
- New YAML loader/dumper pair
- Tests now explicitly cover all loader/dumper pairs

Fixes #66

### CODE REVIEW

**Comment by fzumstein** [comment]
LGTM, the only thing I'd question is if you want to make `pyyaml` a hard dep or maybe just an optional one (`pip install jsondiff[pyyaml]`)?

**Comment by corytodd** [comment]
I did consider that but thought I'd propose a hard dep first. Let me see if there is a clean-ish way to make the YAML features optional without breaking the AP and I'll get back to you.

**Comment by fzumstein** [comment]
It's not a big deal, just thought I'd bring it up.

**Comment by fzumstein** [comment]
There's now a conflict since I merged the rigthonly branch, do you mind fixing this then I can merge. Thanks!

**Comment by corytodd** [comment]
done - I did look into making yaml optional and while doable, I think it will make things more confusing for the end user. For people installing from pip, the new dependency on pyyaml should be transparent, though I understand the desire to minimize dependencies.

**Comment by fzumstein** [comment]
thanks!

**Pull request merged**
